import { FileText } from 'lucide-react';

export const ReportsTemplate = () => {
  return (
    <div className="max-w-7xl mx-auto">
        {/* Page Header */}
        <div className="flex items-center gap-3 mb-6">
          <div className="flex items-center justify-center w-12 h-12 rounded-lg bg-[hsl(var(--color-blue))] text-white">
            <FileText className="w-6 h-6" />
          </div>
          <div>
            <h1 className="text-3xl font-bold text-[hsl(var(--color-gray-900))]">Reports</h1>
            <p className="text-sm text-[hsl(var(--color-gray-500))]">Analytics and business insights</p>
          </div>
        </div>

        {/* Report Categories */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-6">
          {[
            {
              title: 'Sales Report',
              description: 'Monthly sales performance and trends',
              lastGenerated: '2 hours ago',
            },
            {
              title: 'Production Report',
              description: 'Production efficiency and output metrics',
              lastGenerated: '5 hours ago',
            },
            {
              title: 'Inventory Report',
              description: 'Stock levels and inventory turnover',
              lastGenerated: '1 day ago',
            },
            {
              title: 'Quality Report',
              description: 'Quality metrics and defect analysis',
              lastGenerated: '3 hours ago',
            },
            {
              title: 'Financial Report',
              description: 'Revenue, costs, and profitability',
              lastGenerated: '1 week ago',
            },
            {
              title: 'Custom Report',
              description: 'Generate custom reports with filters',
              lastGenerated: 'Never',
            },
          ].map((report, index) => (
            <div
              key={index}
              className="bg-white rounded-lg border border-[hsl(var(--color-gray-200))] p-6 shadow-sm hover:shadow-md transition-shadow cursor-pointer"
            >
              <div className="flex items-start justify-between mb-3">
                <FileText className="w-8 h-8 text-[hsl(var(--color-blue))]" />
              </div>
              <h3 className="text-lg font-semibold text-[hsl(var(--color-gray-900))] mb-2">{report.title}</h3>
              <p className="text-sm text-[hsl(var(--color-gray-600))] mb-3">{report.description}</p>
              <p className="text-xs text-[hsl(var(--color-gray-500))]">
                Last generated: {report.lastGenerated}
              </p>
            </div>
          ))}
        </div>

        {/* Recent Reports */}
        <div className="bg-white rounded-lg border border-[hsl(var(--color-gray-200))] shadow-sm">
          <div className="p-6 border-b border-[hsl(var(--color-gray-200))]">
            <h2 className="text-lg font-semibold text-[hsl(var(--color-gray-900))]">Recent Generated Reports</h2>
          </div>
          <div className="p-6">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="text-left border-b border-[hsl(var(--color-gray-200))]">
                    <th className="pb-3 text-sm font-medium text-[hsl(var(--color-gray-500))]">Report Name</th>
                    <th className="pb-3 text-sm font-medium text-[hsl(var(--color-gray-500))]">Type</th>
                    <th className="pb-3 text-sm font-medium text-[hsl(var(--color-gray-500))]">Generated By</th>
                    <th className="pb-3 text-sm font-medium text-[hsl(var(--color-gray-500))]">Date</th>
                    <th className="pb-3 text-sm font-medium text-[hsl(var(--color-gray-500))]">Status</th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-b border-[hsl(var(--color-gray-100))]">
                    <td className="py-3 text-sm text-[hsl(var(--color-gray-900))]">October Sales Summary</td>
                    <td className="py-3 text-sm text-[hsl(var(--color-gray-700))]">Sales</td>
                    <td className="py-3 text-sm text-[hsl(var(--color-gray-700))]">Admin</td>
                    <td className="py-3 text-sm text-[hsl(var(--color-gray-700))]">Oct 25, 2025</td>
                    <td className="py-3">
                      <span className="px-2 py-1 text-xs rounded-full bg-green-100 text-green-800">Completed</span>
                    </td>
                  </tr>
                  <tr className="border-b border-[hsl(var(--color-gray-100))]">
                    <td className="py-3 text-sm text-[hsl(var(--color-gray-900))]">Weekly Production</td>
                    <td className="py-3 text-sm text-[hsl(var(--color-gray-700))]">Production</td>
                    <td className="py-3 text-sm text-[hsl(var(--color-gray-700))]">Manager</td>
                    <td className="py-3 text-sm text-[hsl(var(--color-gray-700))]">Oct 24, 2025</td>
                    <td className="py-3">
                      <span className="px-2 py-1 text-xs rounded-full bg-green-100 text-green-800">Completed</span>
                    </td>
                  </tr>
                  <tr>
                    <td className="py-3 text-sm text-[hsl(var(--color-gray-900))]">Inventory Audit Q4</td>
                    <td className="py-3 text-sm text-[hsl(var(--color-gray-700))]">Inventory</td>
                    <td className="py-3 text-sm text-[hsl(var(--color-gray-700))]">System</td>
                    <td className="py-3 text-sm text-[hsl(var(--color-gray-700))]">Oct 23, 2025</td>
                    <td className="py-3">
                      <span className="px-2 py-1 text-xs rounded-full bg-blue-100 text-blue-800">Processing</span>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
  )
}
